### ISSUE TITLE
COUPON

### ISSUE THREAD

**Issue by brightigiemokha** [brightigiemokha/bliss_fashion_world#10]
### USER STORY
As a ***User***, I want to ***add Coupon*** to my purchase, so that I can ***get discount*** for my purchases
***
### ACCEPTANCE CRITERIA
- [x] When user input the code a discount is applied to their purchases
- [x] Set a discounted amount based on the coupon code created
***
### TASKS
_A single unit of work broken down from the defined user story_
- [x] Create a coupon feature in the basket for user to input their code
- [x] make the discounted amount visible for user and deducted from purchases
