### ISSUE TITLE
CHECK OUT

### ISSUE THREAD

**Issue by brightigiemokha** [brightigiemokha/bliss_fashion_world#12]
### USER STORY
As a ***User***, I want to ***Check out*** with my selected items, so that I can ***have my purchases delivered*** to my address
***
### ACCEPTANCE CRITERIA
- [x] User can easily and securely check with their selected item
- [x] User can choose the details and address of where item can be delivered
- [x] User can make payment for their pauchases securely using strip
- [x] User get a confirmation and a receipt of purchases
***
### TASKS
- [x] Create a check out page
- [x] Create a table for delivery address and names
- [x] set a secure payment system using strip
