### ISSUE TITLE
ADMIN FEATURES

### ISSUE THREAD

**Issue by brightigiemokha** [brightigiemokha/bliss_fashion_world#13]
### USER STORY
As an ***Admin*** i want to be able to ***control site backend***so as to ***control and maintain*** site and it activities and usage
***
### ACCEPTANCE CRITERIA
- [x] As admin i want to be able to add user
- [x] As admin i want to be able to delete User who violate the site policy 
- [x] As admin i want to be able to create Coupon
- [x] As admin i want to be able to delete Coupon
- [x] As admin i want to be able to add products to Blissful Market site
- [x] As admin i want to be able to delete products from Blissful Market site
- [x] As admin i want to be able to see purchase receipts 
- [x] As admin i want to be able to delete purchase records
***
### TASKS
- [x] Setup and admin data base
