### ISSUE TITLE
USER STORY: LOGIN 

### ISSUE THREAD

**Issue by brightigiemokha** [brightigiemokha/bliss_fashion_world#8]
### USER STORY
As a **Registerred User**, I want to be able to **login** to my **profile account** on the "Blissful Fashion Market" website, so that I can **assess** my profile and **manage my account**.
***
### ACCEPTANCE CRITERIA
- [x]  There is a Login form accessible from the website's homepage.
- [x] The Login form includes fields for username, and password.
- [x]  Passwords are required to meet minimum complexity requirements (8 characters minimum length, at least one uppercase and lowercase letter, numbers, and a special character).
- [x] User can also login using social account (github or Google).

     Validation:
- [x]  Users are alerted with clear error messages if they submit incomplete or invalid data.
- [x]  Users receive an error message if email enterred have not been verified (optional).
- [x]  Users receive an error message if the provided email address is not already registered.
***
### TASKS
- [x] Create the Login form with appropriate fields and styling
- [x]  Implement client-side validation for the Login form.
- [x] Create a success message to display upon successful Login.
- [x] Connect Github and Google Oauth to Login Page
